/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PYuZt7UvTZN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function HeaderNavigation() {
  return (
    <header className="flex items-center justify-between px-4 py-3 bg-background border-b">
      <Link href="#" className="flex items-center gap-2" prefetch={false}>
        <MountainIcon className="w-6 h-6 text-primary" />
        <span className="text-lg font-semibold">Acme Inc</span>
      </Link>
      <nav className="flex items-center gap-6">
        <Link href="/" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
          Home
        </Link>
        <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
          About
        </Link>
        <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
          Services
        </Link>
        <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
          Contact
        </Link>
        <Link href="/login" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
          Login
        </Link>
      </nav>
    </header>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
